#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/a047a4eb-8e09-40be-8fa5-b32a104b8f0a

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float jsPercentage;
  float tsPercentage;
  int buttonPushCounterJS;
  int buttonPushCounterTS;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "tones.h"

#define BUTTON_PIN_TS 5
#define BUTTON_PIN_JS 7
#define BUZZER_PIN 9
#define ONBOARD_LED 13

int buttonStateJS = HIGH; // high because we're using INPUT_PULLUP
int buttonStateTS = HIGH;
int lastButtonStateJS = 0;
int lastButtonStateTS = 0;
bool isConnectedToCloud = false;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);

  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection, false);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();

  pinMode(BUTTON_PIN_JS, INPUT_PULLUP);
  pinMode(BUTTON_PIN_TS, INPUT_PULLUP);
  pinMode(BUZZER_PIN, OUTPUT);
  pinMode(ONBOARD_LED, OUTPUT);
  pinMode(LEDR, OUTPUT);
  pinMode(LEDG, OUTPUT);
  pinMode(LEDB, OUTPUT);

  digitalWrite(ONBOARD_LED, HIGH);
  digitalWrite(LEDG, LOW);
  digitalWrite(LEDR, HIGH);
  playStartTone(BUZZER_PIN);

  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::CONNECT, onConnect);
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::DISCONNECT, onDisconnect);
  
}

void onConnect(){
  /* add your custom code here */
  Serial.println("Board successfully connected to Arduino IoT Cloud");
  isConnectedToCloud = true;
  digitalWrite(ONBOARD_LED, LOW);
  digitalWrite(LEDR, LOW);
  digitalWrite(LEDG, HIGH);
  playConnectionTone(BUZZER_PIN);
}

void onDisconnect(){
  /* add your custom code here */
  Serial.println("Board disconnected from Arduino IoT Cloud");
  digitalWrite(ONBOARD_LED, HIGH);
  digitalWrite(ONBOARD_LED, LOW);
  playDisconnectionTone(BUZZER_PIN);
}

void loop() {
  ArduinoCloud.update();

  if (!isConnectedToCloud) {
    return;
  }
  buttonStateJS = digitalRead(BUTTON_PIN_JS);
  buttonStateTS = digitalRead(BUTTON_PIN_TS);

  if (buttonStateJS != lastButtonStateJS) {
    if (buttonStateJS == LOW) {
      // if the current state is HIGH then the button went from off to on
      digitalWrite(ONBOARD_LED, HIGH);
      buttonPushCounterJS++;
      Serial.print("ON: number of button pushes JS: ");
      Serial.println(buttonPushCounterJS);
      playTone(BUZZER_PIN, 4 * 440, 200); // LA
      updatePercentages(buttonPushCounterJS, buttonPushCounterTS);

    } else {
      Serial.println("OFF JS");
    }
  }
  if (buttonStateTS != lastButtonStateTS) {
    if (buttonStateTS == LOW) {
      digitalWrite(ONBOARD_LED, HIGH);
      // if the current state is HIGH then the button went from off to on
      buttonPushCounterTS++;
      Serial.print("ON: number of button pushes TS: ");
      Serial.println(buttonPushCounterTS);
      playTone(BUZZER_PIN, 5 * 440, 200);
      updatePercentages(buttonPushCounterJS, buttonPushCounterTS);
    } else {
      Serial.println("OFF TS");
    }
  }

  delay(50);
  lastButtonStateJS = buttonStateJS;
  lastButtonStateTS = buttonStateTS;
  digitalWrite(ONBOARD_LED, LOW);
}

void updatePercentages(int buttonPushCounterJS, int buttonPushCounterTS) {
  if (!isConnectedToCloud) {
    return;
  }
  if (buttonPushCounterJS + buttonPushCounterTS > 0) {
    jsPercentage = float(buttonPushCounterJS) / (buttonPushCounterJS + buttonPushCounterTS) * 100;
    tsPercentage = float(buttonPushCounterTS) / (buttonPushCounterJS + buttonPushCounterTS) * 100;
  } else {
    jsPercentage = tsPercentage = 0.0;
  }
  Serial.print("JS%: ");
  Serial.println(jsPercentage);
  Serial.print("TS%: ");
  Serial.println(tsPercentage);
}

/*
  Since ButtonPushCounterJS is READ_WRITE variable, onButtonPushCounterJSChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onButtonPushCounterJSChange() {
  // Add your code here to act upon ButtonPushCounterJS change
  updatePercentages(buttonPushCounterJS, buttonPushCounterTS);
}

/*
  Since ButtonPushCounterTS is READ_WRITE variable, onButtonPushCounterTSChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onButtonPushCounterTSChange() {
  // Add your code here to act upon ButtonPushCounterTS change
  updatePercentages(buttonPushCounterJS, buttonPushCounterTS);
}




/*
  Since TsPercentage is READ_WRITE variable, onTsPercentageChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTsPercentageChange() {
  // Add your code here to act upon TsPercentage change
}


/*
  Since JsPercentage is READ_WRITE variable, onJsPercentageChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onJsPercentageChange() {
  // Add your code here to act upon JsPercentage change
}
